name: Daily Python Script Runner

on:
  # schedule:
  #   - cron: '30 4 * * 1-5'  # 10:00 AM IST
  workflow_dispatch:

jobs:
  short-straddle:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt || true
      - name: Run Short Straddle Bot
        run: python src/test_main_final.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MODE: "production"
          SANDBOX_ACCESS_TOKEN: ${{ secrets.SANDBOX_ACCESS_TOKEN }}

  breakout-buy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt || true
      - name: Run Breakout Buy Bot
        run: python src/breakout_buy.py
        env:
          TOKEN_BUY: ${{ secrets.TOKEN_BUY }}
          SANDBOX_ACCESS_TOKEN: ${{ secrets.SANDBOX_ACCESS_TOKEN }}
          MODE: "production"

  angel-one-short-straddle:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Angel One Short Straddle Bot
        run: python -m src.angel_one_final
        env:
          API_KEY: ${{ secrets.ANGEL_ONE_API_KEY }}
          CLIENT_CODE: ${{ secrets.ANGEL_ONE_CLIENT_CODE }}
          PASSWORD: ${{ secrets.ANGEL_ONE_PASSWORD }}
          TOTP_SECRET: ${{ secrets.ANGEL_ONE_TOTP_SECRET }}
          MODE: "production"
